version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: pgdb@1234
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres 
      # POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    # volumes:
    #   - db:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    
  
  
  
  app:
    image: my-nodejs-backend-app
    ports:
      - 13000:8080




# services: 
#     postgresdb:
#       image: postgres
#       restart: unless-stopped
      
#       environment:
#         POSTGRES_HOST_AUTH_METHOD: "trust"
       
#         POSTGRES_USER: "postgres"
#         POSTGRES_PASSWORD: "pgdb@1234"
#         POSTGRES_DB: "postgres"
#         # - POSTGRES_USER=postgres
#         # - POSTGRES_PASSWORD=pgdb@1234
#         # - POSTGRES_DB=postgres
#       ports:
#         - "5433:5432"
#       volumes:
#         - 'postgresdb:/var/lib/postgresql/data'



#     app:
#       depends_on:
#         - postgresdb
#       build: ./
#       restart: unless-stopped
#       # env_file: ./.env
#       ports:
#         - "8001:8080"
#       environment:
#         - DB_HOST=postgresdb
#         - DB_USER=postgres
#         - DB_PASSWORD=pgdb@1234
#         - DB_NAME=postgres
#         - DB_PORT=5432
#       stdin_open: true
#       tty: true

# volumes:
#   postgresdb: